"""Standalone self-play training script for the dogfight tournament.

Trains a PPO agent in DogfightSelfPlayEnv and writes:
  - results/dogfight/dogfight_ppo_seed{seed}.zip      (SB3 checkpoint)
  - results/dogfight/dogfight_ppo_seed{seed}_meta.json
  - submissions/group_dogfight.py                     (ready to submit)

Usage:
    # Basic run (500k steps, no W&B)
    python train_dogfight.py --seed 0 --no-wandb

    # With W&B logging
    python train_dogfight.py --seed 0

    # Longer run on GPU
    python train_dogfight.py --seed 0 --timesteps 2000000 --device cuda

    # Multiple seeds sequentially
    python train_dogfight.py --seeds 0 1 2 --timesteps 1000000 --no-wandb

    # Parallel environments (4x faster rollout collection)
    python train_dogfight.py --seed 0 --timesteps 500000 --n-envs 4 --no-wandb

Evaluating the trained agent locally:
    # vs random opponent (headless)
    python scripts/evaluate.py --model submissions/group_dogfight.py --env dogfight

    # Render one episode
    python scripts/evaluate.py --model submissions/group_dogfight.py --env dogfight --render
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from implementations.dogfight_ppo import train_selfplay

SUBMISSION_TEMPLATE = '''\
"""Tournament submission — dogfight PPO (self-play trained).

Auto-generated by train_dogfight.py.
Do not edit checkpoint path manually; re-run train_dogfight.py instead.
"""
from __future__ import annotations
from pathlib import Path
import sys

_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

_CHECKPOINT = _PROJECT_ROOT / "results" / "dogfight" / "{checkpoint_name}"


def load_model(path=None):
    """Load the trained dogfight PPO model.

    Args:
        path: optional override path to the .zip checkpoint.

    Returns:
        SB3 PPO model with .predict(obs, deterministic) interface.
          obs:    np.ndarray(37,)
          action: np.ndarray(4,)  — [roll, pitch, yaw, throttle] in [-1, 1]
    """
    from stable_baselines3 import PPO
    return PPO.load(str(path or _CHECKPOINT))
'''


def write_submission(checkpoint_path: Path) -> Path:
    """Write a tournament submission .py file pointing to the checkpoint."""
    submissions_dir = PROJECT_ROOT / "submissions"
    submissions_dir.mkdir(exist_ok=True)
    submission_path = submissions_dir / "group_dogfight.py"

    content = SUBMISSION_TEMPLATE.format(checkpoint_name=checkpoint_path.name)
    submission_path.write_text(content, encoding="utf-8")
    print(f"[train_dogfight] Submission written → {submission_path}")
    return submission_path


def main():
    parser = argparse.ArgumentParser(
        description="Self-play PPO training for the dogfight tournament",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--timesteps", type=int, default=500_000,
                        help="Total training timesteps (default: 500000)")
    parser.add_argument("--seed", type=int, default=0,
                        help="Single random seed (use --seeds for multiple)")
    parser.add_argument("--seeds", nargs="+", type=int,
                        help="Multiple seeds (overrides --seed)")
    parser.add_argument("--device", default="cpu",
                        help="PyTorch device: cpu or cuda (default: cpu)")
    parser.add_argument("--no-wandb", action="store_true",
                        help="Disable Weights & Biases logging")
    parser.add_argument("--output-dir", default=None,
                        help="Output directory for checkpoints (default: results/dogfight/)")
    parser.add_argument("--n-envs", type=int, default=4,
                        help="Number of parallel environments for vectorized training (default: 4)")
    args = parser.parse_args()

    seeds = args.seeds if args.seeds else [args.seed]

    for seed in seeds:
        print(f"\n{'='*60}")
        print(f"  Training dogfight agent  seed={seed}  steps={args.timesteps:,}")
        print(f"{'='*60}")
        checkpoint_path = train_selfplay(
            seed=seed,
            num_timesteps=args.timesteps,
            log_to_wandb=not args.no_wandb,
            output_dir=args.output_dir,
            device=args.device,
            hyperparams_override={"n_envs": args.n_envs},
        )
        # Write / overwrite submission to point at the last trained seed
        write_submission(checkpoint_path)

    print("\n[train_dogfight] Done.")
    print("  To test: python scripts/evaluate.py --model submissions/group_dogfight.py --env dogfight")


if __name__ == "__main__":
    main()
