"""Tournament submission — dogfight PPO (self-play trained).

Auto-generated by train_dogfight.py.
Do not edit checkpoint path manually; re-run train_dogfight.py instead.
"""
from __future__ import annotations
from pathlib import Path
import sys

_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

_CHECKPOINT = _PROJECT_ROOT / "results" / "dogfight" / "dogfight_ppo_seed0.zip"


def load_model(path=None):
    """Load the trained dogfight PPO model.

    Args:
        path: optional override path to the .zip checkpoint.

    Returns:
        SB3 PPO model with .predict(obs, deterministic) interface.
          obs:    np.ndarray(37,)
          action: np.ndarray(4,)  — [roll, pitch, yaw, throttle] in [-1, 1]
    """
    from stable_baselines3 import PPO
    return PPO.load(str(path or _CHECKPOINT))
