_meta:
   algo: ppo_scratch
   task: hover # PyFlyt/QuadX-Hover-v4
   impl: implementations/ppo_implementation.py

PyFlyt/QuadX-Hover-v4:
   n_timesteps: !!float 5e5
   learning_rate: 3.0e-4
   n_steps: 2048 # -> trajectory_length
   gamma: 0.98
   gae_lambda: 0.95
   clip_range: 0.2 # -> clip_ratio
   ent_coef: 0.01 # -> entropy_coef
   vf_coef: 0.5 # -> value_loss_coef
   max_grad_norm: 0.5
   hidden_size: 64
   n_epochs: 10 # -> epochs_per_update
