_meta:
  algo: ppo
  task: waypoints  # PyFlyt/QuadX-Waypoints-v4

PyFlyt/QuadX-Waypoints-v4:
  n_timesteps: !!float 1.5e6
  policy: MlpPolicy
  learning_rate: lin_3e-4
  n_steps: 4096
  batch_size: 128
  gamma: 0.995
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: True
  sde_sample_freq: 4
  normalize: True
  policy_kwargs: "dict(net_arch=dict(pi=[256, 256], vf=[256, 256]))"
  env_kwargs:
    goal_reach_distance: 10.0
    flight_dome_size: 30.0
    max_duration_seconds: 120.0
    num_targets: 2
  env_wrapper:
    - scripts.wrappers.WaypointDistanceShaping:
        shaping_coef: 0.2
    - scripts.wrappers.FlattenWaypointEnv:
        max_waypoints: 4
