_meta:
  algo: ppo
  task: waypoints  # PyFlyt/QuadX-Waypoints-v4

PyFlyt/QuadX-Waypoints-v4:
  n_timesteps: !!float 5e5
  policy: MlpPolicy
  learning_rate: lin_3e-4
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  gae_lambda: 0.98
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  policy_kwargs: "dict(net_arch=dict(pi=[64, 64], vf=[64, 64]))"
  env_kwargs:
    goal_reach_distance: 7.0
    flight_dome_size: 50.0
    max_duration_seconds: 120.0
    num_targets: 2
  env_wrapper:
    - scripts.wrappers.WaypointSumDistanceShaping:
        shaping_coef: 0.2
    - scripts.wrappers.FlattenWaypointEnv:
        max_waypoints: 2
