_meta:
  algo: ppo
  task: hover  # PyFlyt/QuadX-Hover-v4

PyFlyt/QuadX-Hover-v4:
  n_timesteps: !!float 5e5
  policy: MlpPolicy
  learning_rate: 3.0e-4
  n_steps: 4096
  batch_size: 128
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  policy_kwargs: "dict(net_arch=dict(pi=[256, 256], vf=[256, 256]))"
